abort on remote failures

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -147,20 +147,24 @@ deploy() {
 
   # fetch source
   run "cd $path/source && git fetch origin && git reset --hard $ref"
+  test $? -eq 0 || abort 'fetch failed'
 
   # link current
   run "ln -sf $path/source $path/current"
+  test $? -eq 0 || abort 'symlink failed'
 
   # deploy log
   run "cd $path/source && \
       echo \`git rev-parse --short HEAD\` \
       >> $path/.deploys"
+  test $? -eq 0 || abort 'deploy log append failed'
 
   # post-deploy
   local cmd=`config_get post-deploy`
   if test -n "$cmd"; then
     log "executing post-deploy $ $cmd"
     run "cd $path/current && $cmd"
+    test $? -eq 0 || abort 'post-deploy hook failed'
   fi
 
   # done
